# La receta del modelo (estándar para Rasa 3.x)
recipe: default.v1

# Identificador único de tu asistente (puedes cambiarlo si quieres)
assistant_id: chatbot-adiccion-redes

# Idioma de tu asistente
language: es

# --- Configuración del Pipeline de NLU ---
# Aquí definimos, en orden, cómo se procesa el texto del usuario.
pipeline:
  # 1. Tokenizador: Divide el texto en palabras/tokens.
  - name: WhitespaceTokenizer

  # 2. Featurizers: Crean representaciones numéricas del texto.
  #    Estos deben ir DESPUÉS del Tokenizer.
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4

  # 3. Clasificador principal: Usa las features para predecir intenciones y entidades.
  - name: DIETClassifier
    epochs: 100
    entity_recognition: True

  # 4. Selector de respuestas: Se usa para chit-chat y FAQs.
  #    También necesita los featurizers, por eso va después de ellos.
  - name: ResponseSelector
    epochs: 100

  # 5. Mapeador de sinónimos: Reemplaza sinónimos (ej. "NY" -> "New York").
  - name: EntitySynonymMapper

  # 6. Clasificador de fallback: Se activa si la confianza es muy baja.
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1


# --- Configuración de las Políticas de Core ---
# Aquí definimos cómo el bot decide qué acción tomar a continuación.
policies:
  # 1. RulePolicy: Sigue las reglas de tu archivo rules.yml de forma estricta.
  - name: RulePolicy
    core_fallback_action_name: "action_default_fallback"
    core_fallback_threshold: 0.4

  # 2. MemoizationPolicy: Recuerda las conversaciones de tus stories.
  - name: MemoizationPolicy
    max_history: 5

  # 3. TEDPolicy: Una red neuronal que generaliza a partir de tus stories
  #    para manejar conversaciones que no ha visto antes.
  - name: TEDPolicy
    max_history: 5
    epochs: 100